### PR TITLE
Update gtuber lib

### PR DESCRIPTION
**Pull request by X-m7**
Fixes issue with YouTube playback.

https://github.com/Rafostar/clapper/issues/401

### CODE REVIEW

**Comment by X-m7** [comment]
Argh, Flathub's new validation policies bites again:

```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption",
        "finish-args-redundant-device-all",
        "appstream-summary-too-long"
    ],
    "appstream": [
        "W: com.github.rafostar.Clapper:234: relation-display-length-value-invalid small",
        "E: com.github.rafostar.Clapper:238: custom-key-duplicated Purism::form_factor"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by X-m7** [comment]
Just tested the build on my PinePhone running postmarketOS 23.12, and indeed YouTube playback works again. A nice side effect of the metainfo patch is that GNOME Software now shows the app as "Adaptive" instead of saying that it only works on desktops and laptops.

Also, the source URL for liba52 results in a 404 error now, so I can't build the flatpak locally, I guess Flathub has its own cache for that stuff.

**Comment by Rafostar** [comment]
@X-m7 Are `Purism::form_factor` no longer needed? If I remember correctly, last time they were requested to be added, as Phosh had an option to show only mobile friendly apps in drawer and these were needed or something like that.

**Comment by X-m7** [comment]
The option for it still exists, but it's no longer the default, since now Phosh supports forcibly scaling down any apps that end up being too big so non mobile friendly apps isn't much of a problem anymore.

Alternatively, since the validation problem is just that there can't be both the `workstation` and `mobile` entries together, maybe just having `mobile` would be fine?

**Comment by X-m7** [comment]
For what it's worth I just tried removing the current Flathub version of Clapper and only having the test build installed, rebooted, and then enabling the application filter, after that Clapper still appears in the app list while things like LibreOffice disappears. so the filter is definitely working.

Some googling also seems to indicate that Phosh looks at the desktop file rather than the metainfo file to check whether an app is "mobile friendly", by looking for `X-Purism-FormFactor=Workstation;Mobile;`, so I don't think the metainfo change does much these days.

As mentioned before GNOME Software doesn't look at it either, it seems to check the `display_length` value to decide whether an app is adaptive or not.

**Comment by X-m7** [comment]
Just asked in the Phosh Matrix room about it (Guido is one of the Phosh devs):

image

**Comment by Rafostar** [comment]
> For what it's worth I just tried removing the current Flathub version of Clapper and only having the test build installed, rebooted, and then enabling the application filter, after that Clapper still appears in the app list while things like LibreOffice disappears. so the filter is definitely working.

Thanks for checking. Also, according to discussion in: https://github.com/ximion/appstream/issues/476 they indeed should be removed nowadays and other apps are removing them too.

**Pull request merged**
